[package]
name = "cli_ll_protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.ll_protocol]
path="../../driverslib/ll_protocol"

[dependencies]
ctrlc = "3.4.2"
hex = "0.4.3"
serialport = "4.3.0"
