name: Rust

on:
  push:
    branches: []
  pull_request:
    branches: []

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install APT Packages Dependencies
      run: sudo apt-get update && sudo apt-get install -y libudev-dev pkg-config libssl-dev libopencv-dev clang libclang-dev
    
    - name: Build driverslib
      working-directory: ./driverslib/ll_protocol
      run: cargo build --verbose
    - name: Run driverslib tests
      working-directory: ./driverslib/ll_protocol
      run: cargo test --verbose
      
    - name: Build application
      working-directory: ./
      run: cargo build --verbose
    - name: Run application tests
      working-directory: ./
      run: cargo test --verbose

    - name: Build cli_ll_protocol
      working-directory: ./tools/cli_ll_protocol
      run: cargo build --verbose
